name: Run JavaScript Script

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * *'  # UTC 3:00，北京时间 11:00
    - cron: '30 6 * * *'   # UTC 6:30，北京时间 15:30

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Node.js script
        run: node -e "console.log(process.env.TOS_ACCESS_KEY_ID)" # 直接测试
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Use secret in script
        env:
          TOS_ACCESS_KEY_ID: ${{ secrets.TOS_ACCESS_KEY_ID }}
          TOS_ACCESS_KEY_SECRET: ${{ secrets.TOS_ACCESS_KEY_SECRET }}
        run: echo "Secret key has load"

      - name: Install dependencies
        run: npm install  # 如果有依赖需要安装

      - name: Run JavaScript script
        run: node ciScript.js